theme_advanced_toolbar_location: 'none'
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: 'none'
#statusbar : false
theme_advanced_font_sizes: "10px,12px,13px,14px,16px,18px,20px"
font_size_style_values: "12px,13px,14px,16px,18px,20px"

menubar : false
theme_advanced_buttons3_add:
  - fullscreen
plugins:
  - fullscreen